name: flutter_srt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  http: ^1.2.0
  injectable: ^2.3.2
  provider: ^6.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.2


flutter:
  uses-material-design: true
  assets: 
   - assets/images/openobjectLogo.png
   - assets/images/srtLogo.png
   - assets/images/ico_login_checked_n.png
   - assets/images/ico_login_checked_y.png
   - assets/images/navi_close_button.png