name: flutter_srt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.2.1
  http: ^1.2.0
  injectable: ^2.3.2
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.2


flutter:
  uses-material-design: true
  assets: 
   - assets/images/
  fonts:
  - family: SpoqaHanSansNeo
    fonts: 
    - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf
      weight: 400
    - asset: assets/fonts/SpoqaHanSansNeo-Medium.ttf
      weight: 500
    - asset: assets/fonts/SpoqaHanSansNeo-Bold.ttf
      weight: 700
